# Generated by Django 2.0.3 on 2018-05-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_to_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='to_floor',
        ),
    ]
