# Generated by Django 2.0.3 on 2018-05-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180507_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
