# Generated by Django 2.0.3 on 2018-05-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
