# Generated by Django 2.0.3 on 2018-05-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinds',
            name='to_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_kinds', to='category.Category'),
        ),
    ]
