# Generated by Django 2.0.3 on 2018-05-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20180507_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='to_kinds',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='to_kinds',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
