# Generated by Django 2.0.3 on 2018-05-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20180507_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('to_kinds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_category', to='category.Kinds')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('to_kinds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_floor', to='category.Kinds')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
