# Generated by Django 2.0.3 on 2018-05-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='to_kinds',
        ),
        migrations.RemoveField(
            model_name='kinds',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='floor',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kinds',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
