# Generated by Django 2.0.3 on 2018-05-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20180507_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='to_kinds',
        ),
        migrations.AddField(
            model_name='kinds',
            name='to_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c_kinds', to='category.Category'),
            preserve_default=False,
        ),
    ]
