# Generated by Django 2.0.3 on 2018-05-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20180507_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('floor',)},
        ),
        migrations.AlterField(
            model_name='category',
            name='floor',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
